var letter_1="S";
console.log(letter_1);
var letter_2="h";
console.log(letter_2);
var letter_3="i";
console.log(letter_3);
var letter_4="v"
console.log(letter_4);
var letter_5="a";
console.log(letter_5);
var letter_6="m";
console.log(letter_6);
var name=letter_1.concat(letter_2,letter_3,letter_4,letter_5,letter_6);
console.log(name);
var name_length=name.length;
console.log(name_length);
var word="Hi";
console.log(word);
var name_replace=word.replace("Hi","Bye");
console.log(name_replace);
var word_2="QWERTY keyboard";
console.log(word_2);
var lower_case=word_2.toLowerCase();
console.log(lower_case);
var word_3="qwerty KEYBOARD";
console.log(word_3);
var upper_case=word_3.toUpperCase();
console.log(upper_case);
var number_1=Math.sqrt(1240867);
console.log(number_1);
var number_2=Math.max(485638,4327569237458475,38573786);
console.log(number_2);
var number_3=Math.min(-218462918736,-24673287278,-4586702875034);
console.log(m=number_3);
var x=Math.floor((Math.random()*100)+1);
console.log(x);
var y=Math.floor((Math.random()*100)+1);
console.log(y);
var add=x+y;
console.log(add);
var x=Math.floor((Math.random()*100)+1);
console.log(x);
var y=Math.floor((Math.random()*100)+1);
console.log(y);
var sub=x-y;
console.log(sub);
var x=Math.floor((Math.random()*100)+1);
console.log(x);
var y=Math.floor((Math.random()*100)+1);
console.log(y);
var mul=x*y;
console.log(mul);
var x=Math.floor((Math.random()*100)+1);
console.log(x);
var y=Math.floor((Math.random()*100)+1);
console.log(y);
var div=x/y;
console.log(div);
var x=Math.floor((Math.random()*100)+1);
console.log(x);
var y= Math.floor((Math.random()*100)+1);
console.log(y);
var pow=x**y;
console.log(pow);

